---
- name: Deploy App
  hosts: app
  become: true
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith # <-- Указываем нужную ветку
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit  # <-- В какой директории выполнять команду bundle

  handlers:
  - name: reload puma
    become: true
    systemd:
      state: reloaded
      daemon_reload: yes
      name: puma
