---
- name: Install Ruby && Bundler && Git
  hosts: all
  become: true
  tasks:
    - name: Install ruby and rubygems and required packages and git
      apt:
        name:
          - git
          - ruby-full
          - ruby-bundler
          - build-essential
        update_cache: yes
        state: present
